"""added signal strenght updates in sensor_reading

Revision ID: 039635e8f58e
Revises: 2fd535665fdd
Create Date: 2025-12-20 13:09:39.365458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '039635e8f58e'
down_revision: Union[str, Sequence[str], None] = '2fd535665fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_readings', sa.Column('signal_strength', sa.Integer(), nullable=True))
    op.add_column('sensor_readings', sa.Column('signal_quality', sa.String(length=20), nullable=True))
    op.drop_constraint(op.f('sensor_readings_sensor_id_fkey'), 'sensor_readings', type_='foreignkey')
    op.create_foreign_key(None, 'sensor_readings', 'sensor_devices', ['sensor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensor_readings', type_='foreignkey')
    op.create_foreign_key(op.f('sensor_readings_sensor_id_fkey'), 'sensor_readings', 'sensor_devices', ['sensor_id'], ['id'])
    op.drop_column('sensor_readings', 'signal_quality')
    op.drop_column('sensor_readings', 'signal_strength')
    # ### end Alembic commands ###
