"""initial migration

Revision ID: 04a04e3a9b02
Revises: 
Create Date: 2026-02-28 13:47:13.132761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04a04e3a9b02'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('force_password_change', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_by', sa.UUID(), nullable=True),
    sa.Column('deactivation_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['deactivated_by'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('notification_dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('WARNING', 'CRITICAL', 'BLOCKAGE', 'ANNOUNCEMENT', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_dispatches_id'), 'notification_dispatches', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('json_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=225), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camera_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id')
    )
    op.create_table('daily_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('min_risk_score', sa.Integer(), nullable=True),
    sa.Column('max_risk_score', sa.Integer(), nullable=True),
    sa.Column('min_risk_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_risk_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('min_debris_count', sa.Integer(), nullable=True),
    sa.Column('max_debris_count', sa.Integer(), nullable=True),
    sa.Column('min_debris_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_debris_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('least_severe_blockage', sa.String(), nullable=True),
    sa.Column('most_severe_blockage', sa.String(), nullable=True),
    sa.Column('min_water_level_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_water_level_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('min_water_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_water_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('min_precipitation_mm', sa.Float(), nullable=True),
    sa.Column('max_precipitation_mm', sa.Float(), nullable=True),
    sa.Column('min_precip_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_precip_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('most_severe_weather_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'summary_date', name='uq_location_date')
    )
    op.create_index(op.f('ix_daily_summaries_summary_date'), 'daily_summaries', ['summary_date'], unique=False)
    op.create_table('notification_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('WARNING', 'CRITICAL', 'BLOCKAGE', 'ANNOUNCEMENT', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_templates_id'), 'notification_templates', ['id'], unique=False)
    op.create_index('uq_notification_templates_single_system_template_type', 'notification_templates', ['type'], unique=True, postgresql_where=sa.text("type IN ('WARNING', 'CRITICAL', 'BLOCKAGE')"))
    op.create_table('password_reset_otps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('responders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', name='responderstatus'), nullable=False),
    sa.Column('location_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notif_preferences', sa.JSON(), server_default=sa.text('\'{"warning": true, "critical": true, "blockage": true, "announcement": true}\'::json'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('sensor_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('sensor_config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id')
    )
    op.create_table('weather',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('precipitation_mm', sa.Float(), nullable=False),
    sa.Column('weather_code', sa.Integer(), nullable=False),
    sa.Column('temperature_2m', sa.Float(), nullable=False),
    sa.Column('relative_humidity_2m', sa.Float(), nullable=False),
    sa.Column('wind_speed_10m', sa.Float(), nullable=False),
    sa.Column('wind_direction_10m', sa.Float(), nullable=False),
    sa.Column('cloud_cover', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_device_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('blockage_percentage', sa.Float(), nullable=False),
    sa.Column('blockage_status', sa.String(), nullable=False),
    sa.Column('total_debris_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['camera_device_id'], ['camera_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('responder_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.ForeignKeyConstraint(['responder_id'], ['responders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('responder_id', 'endpoint', name='uq_push_subscription_responder_endpoint')
    )
    op.create_table('responder_groups',
    sa.Column('responder_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responder_id'], ['responders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('responder_id', 'group_id')
    )
    op.create_table('responders_otp_verification',
    sa.Column('responder_id', sa.UUID(), nullable=False),
    sa.Column('otp_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['responder_id'], ['responders.id'], ),
    sa.PrimaryKeyConstraint('responder_id')
    )
    op.create_index(op.f('ix_responders_otp_verification_responder_id'), 'responders_otp_verification', ['responder_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sensor_device_id', sa.Integer(), nullable=False),
    sa.Column('water_level_cm', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('raw_distance_cm', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('signal_strength', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.ForeignKeyConstraint(['sensor_device_id'], ['sensor_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_id'), 'sensor_readings', ['id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_timestamp'), 'sensor_readings', ['timestamp'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('responder_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='deliverystatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_id'], ['notification_dispatches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responder_id'], ['responders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['push_subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dispatch_id', 'responder_id', name='uq_delivery_dispatch_responder'),
    sa.UniqueConstraint('id', 'responder_id', name='uq_delivery_id_responder')
    )
    op.create_index('ix_notification_deliveries_responder_status', 'notification_deliveries', ['responder_id', 'status'], unique=False)
    op.create_table('acknowledgements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('responder_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id', 'responder_id'], ['notification_deliveries.id', 'notification_deliveries.responder_id'], name='fk_acknowledgements_delivery_responder', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['delivery_id'], ['notification_deliveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responder_id'], ['responders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id', name='uq_acknowledgement_delivery')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acknowledgements')
    op.drop_index('ix_notification_deliveries_responder_status', table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index(op.f('ix_sensor_readings_timestamp'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_responders_otp_verification_responder_id'), table_name='responders_otp_verification')
    op.drop_table('responders_otp_verification')
    op.drop_table('responder_groups')
    op.drop_table('push_subscriptions')
    op.drop_table('model_readings')
    op.drop_table('weather')
    op.drop_table('sensor_devices')
    op.drop_table('responders')
    op.drop_table('refresh_tokens')
    op.drop_table('password_reset_otps')
    op.drop_index('uq_notification_templates_single_system_template_type', table_name='notification_templates', postgresql_where=sa.text("type IN ('WARNING', 'CRITICAL', 'BLOCKAGE')"))
    op.drop_index(op.f('ix_notification_templates_id'), table_name='notification_templates')
    op.drop_table('notification_templates')
    op.drop_index(op.f('ix_daily_summaries_summary_date'), table_name='daily_summaries')
    op.drop_table('daily_summaries')
    op.drop_table('camera_devices')
    op.drop_table('admin_audit_logs')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_notification_dispatches_id'), table_name='notification_dispatches')
    op.drop_table('notification_dispatches')
    op.drop_table('locations')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
