"""added push subscription and notif_delivery

Revision ID: 0769ed28c5b0
Revises: 7d065044f43f
Create Date: 2026-02-25 04:07:59.718355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0769ed28c5b0'
down_revision: Union[str, Sequence[str], None] = '7d065044f43f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'title')
    # ### end Alembic commands ###
