"""added responder notif preference

Revision ID: 2f79870a7015
Revises: a4d4de625cee
Create Date: 2026-02-24 14:15:42.901001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f79870a7015'
down_revision: Union[str, Sequence[str], None] = 'a4d4de625cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responders', sa.Column('notif_preferences', sa.JSON(), server_default=sa.text('\'{"warning": true, "critical": true, "blockage": true, "announcement": true}\'::json'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responders', 'notif_preferences')
    # ### end Alembic commands ###
