"""used responder_id for responder_otp_verification

Revision ID: 3a43372e2e45
Revises: c93f8278f73b
Create Date: 2026-02-14 18:05:55.559876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a43372e2e45'
down_revision: Union[str, Sequence[str], None] = 'c93f8278f73b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responders_otp_verification', sa.Column('responder_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_responders_otp_verification_phone_number'), table_name='responders_otp_verification')
    op.create_index(op.f('ix_responders_otp_verification_responder_id'), 'responders_otp_verification', ['responder_id'], unique=False)
    op.create_foreign_key(None, 'responders_otp_verification', 'responders', ['responder_id'], ['id'])
    op.drop_column('responders_otp_verification', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responders_otp_verification', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'responders_otp_verification', type_='foreignkey')
    op.drop_index(op.f('ix_responders_otp_verification_responder_id'), table_name='responders_otp_verification')
    op.create_index(op.f('ix_responders_otp_verification_phone_number'), 'responders_otp_verification', ['phone_number'], unique=False)
    op.drop_column('responders_otp_verification', 'responder_id')
    # ### end Alembic commands ###
