"""made the auto_send flags of message template nullable

Revision ID: 4c7f9e00b729
Revises: dfa96b98185e
Create Date: 2026-02-15 12:02:20.486631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7f9e00b729'
down_revision: Union[str, Sequence[str], None] = 'dfa96b98185e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_templates', 'auto_send_on_warning',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('message_templates', 'auto_send_on_critical',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('message_templates', 'auto_send_on_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_templates', 'auto_send_on_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('message_templates', 'auto_send_on_critical',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('message_templates', 'auto_send_on_warning',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
