"""add_daily_summaries_table

Revision ID: 598b2a917e6b
Revises: 9abbfd776794
Create Date: 2026-02-15 14:29:38.810455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598b2a917e6b'
down_revision: Union[str, Sequence[str], None] = '9abbfd776794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('min_risk_score', sa.Integer(), nullable=True),
    sa.Column('max_risk_score', sa.Integer(), nullable=True),
    sa.Column('min_risk_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_risk_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('min_debris_count', sa.Integer(), nullable=True),
    sa.Column('max_debris_count', sa.Integer(), nullable=True),
    sa.Column('min_debris_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_debris_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('least_severe_blockage', sa.String(), nullable=True),
    sa.Column('most_severe_blockage', sa.String(), nullable=True),
    sa.Column('min_water_level_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_water_level_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('min_water_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_water_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('min_precipitation_mm', sa.Float(), nullable=True),
    sa.Column('max_precipitation_mm', sa.Float(), nullable=True),
    sa.Column('min_precip_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_precip_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('most_severe_weather_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'summary_date', name='uq_location_date')
    )
    op.create_index(op.f('ix_daily_summaries_summary_date'), 'daily_summaries', ['summary_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_summaries_summary_date'), table_name='daily_summaries')
    op.drop_table('daily_summaries')
    # ### end Alembic commands ###
