"""add message_template auto_send unique partial indexes

Revision ID: 9abbfd776794
Revises: 4c7f9e00b729
Create Date: 2026-02-15 12:14:19.641963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9abbfd776794'
down_revision: Union[str, Sequence[str], None] = '4c7f9e00b729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_message_templates_auto_send_blocked_true', 'message_templates', ['auto_send_on_blocked'], unique=True, postgresql_where=sa.text('auto_send_on_blocked IS true'))
    op.create_index('uq_message_templates_auto_send_critical_true', 'message_templates', ['auto_send_on_critical'], unique=True, postgresql_where=sa.text('auto_send_on_critical IS true'))
    op.create_index('uq_message_templates_auto_send_warning_true', 'message_templates', ['auto_send_on_warning'], unique=True, postgresql_where=sa.text('auto_send_on_warning IS true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_message_templates_auto_send_warning_true', table_name='message_templates', postgresql_where=sa.text('auto_send_on_warning IS true'))
    op.drop_index('uq_message_templates_auto_send_critical_true', table_name='message_templates', postgresql_where=sa.text('auto_send_on_critical IS true'))
    op.drop_index('uq_message_templates_auto_send_blocked_true', table_name='message_templates', postgresql_where=sa.text('auto_send_on_blocked IS true'))
    # ### end Alembic commands ###
