"""added location_id to responders

Revision ID: a4d4de625cee
Revises: f91a4965931f
Create Date: 2026-02-21 22:14:38.129511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d4de625cee'
down_revision: Union[str, Sequence[str], None] = 'f91a4965931f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responders', sa.Column('location_id', sa.Integer(), server_default='1', nullable=False))
    op.create_foreign_key(None, 'responders', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'responders', type_='foreignkey')
    op.drop_column('responders', 'location_id')
    # ### end Alembic commands ###
