"""fixed the join relationship of responder and group

Revision ID: c6c1d1784405
Revises: 3a43372e2e45
Create Date: 2026-02-14 19:31:49.114191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6c1d1784405'
down_revision: Union[str, Sequence[str], None] = '3a43372e2e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('responder_groups_group_id_fkey'), 'responder_groups', type_='foreignkey')
    op.drop_constraint(op.f('responder_groups_responder_id_fkey'), 'responder_groups', type_='foreignkey')
    op.create_foreign_key(None, 'responder_groups', 'responders', ['responder_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'responder_groups', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'responder_groups', type_='foreignkey')
    op.drop_constraint(None, 'responder_groups', type_='foreignkey')
    op.create_foreign_key(op.f('responder_groups_responder_id_fkey'), 'responder_groups', 'responders', ['responder_id'], ['id'])
    op.create_foreign_key(op.f('responder_groups_group_id_fkey'), 'responder_groups', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
