"""modified responders model

Revision ID: c93f8278f73b
Revises: ec72abe996e2
Create Date: 2026-02-12 22:43:18.113767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c93f8278f73b'
down_revision: Union[str, Sequence[str], None] = 'ec72abe996e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responders', sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('responders', sa.Column('created_by', sa.UUID(), nullable=False))
    
    # Create new enum type
    op.execute("CREATE TYPE responderstatus AS ENUM ('PENDING', 'ACTIVE')")
    
    # Alter column with value mapping using USING clause
    op.execute("""
        ALTER TABLE responders 
        ALTER COLUMN status TYPE responderstatus 
        USING (
            CASE status::text
                WHEN 'pending' THEN 'PENDING'::responderstatus
                WHEN 'approved' THEN 'ACTIVE'::responderstatus
            END
        )
    """)
    
    # Drop old enum type
    op.execute("DROP TYPE responder_status")
    
    op.drop_constraint(op.f('responders_approved_by_fkey'), 'responders', type_='foreignkey')
    op.create_foreign_key(None, 'responders', 'admin_users', ['created_by'], ['id'])
    op.drop_column('responders', 'approved_by')
    op.drop_column('responders', 'id_photo_path')
    op.drop_column('responders', 'approved_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responders', sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('responders', sa.Column('id_photo_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('responders', sa.Column('approved_by', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'responders', type_='foreignkey')
    op.create_foreign_key(op.f('responders_approved_by_fkey'), 'responders', 'admin_users', ['approved_by'], ['id'])
    
    # Create old enum type
    op.execute("CREATE TYPE responder_status AS ENUM ('pending', 'approved')")
    
    # Alter column back with value mapping
    op.execute("""
        ALTER TABLE responders 
        ALTER COLUMN status TYPE responder_status 
        USING (
            CASE status::text
                WHEN 'PENDING' THEN 'pending'::responder_status
                WHEN 'ACTIVE' THEN 'approved'::responder_status
            END
        )
    """)
    
    # Drop new enum type
    op.execute("DROP TYPE responderstatus")
    
    op.drop_column('responders', 'created_by')
    op.drop_column('responders', 'activated_at')
    # ### end Alembic commands ###
