"""added two auto send options for message template

Revision ID: dfa96b98185e
Revises: c6c1d1784405
Create Date: 2026-02-15 11:41:36.771015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa96b98185e'
down_revision: Union[str, Sequence[str], None] = 'c6c1d1784405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_templates', sa.Column('auto_send_on_warning', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('message_templates', sa.Column('auto_send_on_blocked', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_templates', 'auto_send_on_blocked')
    op.drop_column('message_templates', 'auto_send_on_warning')
    # ### end Alembic commands ###
